/**
 * Facility registry — schools & health facilities for children's early warning.
 * Seed data for Kampala pilot wards. In production this would live in Postgres/Strapi.
 */

export const FACILITIES = [
  {
    id: "sch-kawempe-primary",
    name: "Kawempe Church of Uganda Primary School",
    type: "school",
    ward: "Kawempe",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3775,
    lng: 32.5572,
    enrollment: 1240,
    contactRole: "Headteacher",
    stationId: "stn-kawempe-01",
    drainageVulnerability: 0.72,
    urbanHeatIslandDelta: 5.1,
    treeCanopyCoverage: 0.04,
    imperviousSurface: 0.78,
  },
  {
    id: "sch-bwaise-muslim",
    name: "Bwaise Muslim Primary School",
    type: "school",
    ward: "Bwaise",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3538,
    lng: 32.5615,
    enrollment: 890,
    contactRole: "Headteacher",
    stationId: "stn-bwaise-01",
    drainageVulnerability: 0.88,
    urbanHeatIslandDelta: 5.4,
    treeCanopyCoverage: 0.03,
    imperviousSurface: 0.85,
  },
  {
    id: "sch-katanga-community",
    name: "Katanga Community School",
    type: "school",
    ward: "Katanga",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3352,
    lng: 32.5738,
    enrollment: 620,
    contactRole: "Headteacher",
    stationId: "stn-katanga-01",
    drainageVulnerability: 0.65,
    urbanHeatIslandDelta: 6.8,
    treeCanopyCoverage: 0.02,
    imperviousSurface: 0.9,
  },
  {
    id: "sch-namuwongo-baptist",
    name: "Namuwongo Baptist Primary",
    type: "school",
    ward: "Namuwongo",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3015,
    lng: 32.6058,
    enrollment: 780,
    contactRole: "Headteacher",
    stationId: "stn-namuwongo-01",
    drainageVulnerability: 0.82,
    urbanHeatIslandDelta: 4.6,
    treeCanopyCoverage: 0.05,
    imperviousSurface: 0.76,
  },
  {
    id: "sch-kisenyi-nursery",
    name: "Kisenyi Nursery & Primary",
    type: "school",
    ward: "Kisenyi",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3128,
    lng: 32.5682,
    enrollment: 540,
    contactRole: "Headteacher",
    stationId: "stn-kisenyi-01",
    drainageVulnerability: 0.7,
    urbanHeatIslandDelta: 6.2,
    treeCanopyCoverage: 0.02,
    imperviousSurface: 0.88,
  },
  {
    id: "sch-kalerwe-secondary",
    name: "Kalerwe Secondary School",
    type: "school",
    ward: "Kalerwe",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3612,
    lng: 32.5718,
    enrollment: 1100,
    contactRole: "Headteacher",
    stationId: "stn-kalerwe-01",
    drainageVulnerability: 0.68,
    urbanHeatIslandDelta: 3.9,
    treeCanopyCoverage: 0.07,
    imperviousSurface: 0.7,
  },
  {
    id: "sch-makerere-college",
    name: "Makerere College School",
    type: "school",
    ward: "Makerere",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3336,
    lng: 32.5675,
    enrollment: 2100,
    contactRole: "Headteacher",
    stationId: null,
    drainageVulnerability: 0.35,
    urbanHeatIslandDelta: 3.2,
    treeCanopyCoverage: 0.18,
    imperviousSurface: 0.55,
  },
  {
    id: "sch-nakawa-primary",
    name: "Nakawa Primary School",
    type: "school",
    ward: "Nakawa",
    district: "Kampala",
    country: "Uganda",
    lat: 0.332,
    lng: 32.6155,
    enrollment: 960,
    contactRole: "Headteacher",
    stationId: "stn-nakawa-01",
    drainageVulnerability: 0.55,
    urbanHeatIslandDelta: 4.0,
    treeCanopyCoverage: 0.1,
    imperviousSurface: 0.65,
  },
  {
    id: "cli-kawempe-hciv",
    name: "Kawempe Health Centre IV",
    type: "clinic",
    ward: "Kawempe",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3798,
    lng: 32.5591,
    enrollment: 0,
    catchment: 45000,
    contactRole: "In-charge",
    stationId: "stn-kawempe-clinic-01",
    drainageVulnerability: 0.7,
    urbanHeatIslandDelta: 5.0,
    treeCanopyCoverage: 0.06,
    imperviousSurface: 0.72,
  },
  {
    id: "cli-mulago-paeds",
    name: "Mulago Paediatric Outpatient Unit",
    type: "clinic",
    ward: "Mulago",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3389,
    lng: 32.5756,
    enrollment: 0,
    catchment: 120000,
    contactRole: "Paediatric Lead",
    stationId: "stn-mulago-01",
    drainageVulnerability: 0.4,
    urbanHeatIslandDelta: 4.2,
    treeCanopyCoverage: 0.12,
    imperviousSurface: 0.68,
  },
  {
    id: "cli-kiswa-hc",
    name: "Kiswa Health Centre III",
    type: "clinic",
    ward: "Nakawa",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3245,
    lng: 32.6088,
    enrollment: 0,
    catchment: 28000,
    contactRole: "In-charge",
    stationId: "stn-kiswa-01",
    drainageVulnerability: 0.58,
    urbanHeatIslandDelta: 4.1,
    treeCanopyCoverage: 0.08,
    imperviousSurface: 0.7,
  },
  {
    id: "cli-kisenyi-hc",
    name: "Kisenyi Health Centre IV",
    type: "clinic",
    ward: "Kisenyi",
    district: "Kampala",
    country: "Uganda",
    lat: 0.3142,
    lng: 32.5695,
    enrollment: 0,
    catchment: 52000,
    contactRole: "In-charge",
    stationId: null,
    drainageVulnerability: 0.75,
    urbanHeatIslandDelta: 6.0,
    treeCanopyCoverage: 0.03,
    imperviousSurface: 0.86,
  },
];

export function listFacilities({ type, ward, district } = {}) {
  return FACILITIES.filter((f) => {
    if (type && f.type !== type) return false;
    if (ward && f.ward.toLowerCase() !== ward.toLowerCase()) return false;
    if (district && f.district.toLowerCase() !== district.toLowerCase()) return false;
    return true;
  });
}

export function getFacility(id) {
  return FACILITIES.find((f) => f.id === id) || null;
}

export function facilityStats() {
  const schools = FACILITIES.filter((f) => f.type === "school");
  const clinics = FACILITIES.filter((f) => f.type === "clinic");
  const childrenCovered = schools.reduce((s, f) => s + (f.enrollment || 0), 0);
  const catchment = clinics.reduce((s, f) => s + (f.catchment || 0), 0);
  const withStations = FACILITIES.filter((f) => f.stationId).length;
  const wards = [...new Set(FACILITIES.map((f) => f.ward))];
  return {
    total: FACILITIES.length,
    schools: schools.length,
    clinics: clinics.length,
    childrenCovered,
    clinicCatchment: catchment,
    facilitiesWithStations: withStations,
    wards: wards.length,
    wardList: wards,
  };
}

export function publicFacility(f) {
  return {
    id: f.id,
    name: f.name,
    type: f.type,
    ward: f.ward,
    district: f.district,
    country: f.country,
    lat: f.lat,
    lng: f.lng,
    enrollment: f.enrollment || 0,
    catchment: f.catchment || 0,
    contactRole: f.contactRole,
    hasStation: Boolean(f.stationId),
    stationId: f.stationId || null,
  };
}
